# permissions for end users to view crontabs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crontab-viewer-role
rules:
- apiGroups:
  - stable.example.com.k8s.io
  resources:
  - crontabs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stable.example.com.k8s.io
  resources:
  - crontabs/status
  verbs:
  - get
